const radioEpisodes = [
  {
    date: 'June 19, 2012',
    title: 43,
    description: 'Capital Region’s Integrative Medicine Specialist Dr. Chris Link talks about some common medical misconceptions in our latest conversation on KWOS OPEN AIR:',
    duration: '13:14',
    station: 'KWOS',
    name: 'KWOS_2012_06_19',
  },
  {
    date: 'July 17, 2012',
    title: 44,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2012_07_17',
  },
  {
    date: 'August 21, 2012',
    title: 45,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2012_08_21',
  },
  {
    date: 'September 18, 2012',
    title: 46,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2012_09_18',
  },
  // {
  //   date: 'October 23, 2012',
  //   title: 47,
  //   description: 'What happens when the kids don’t get enough sleep? You can’t get them up for school the next day, and when you do… they’re bouncing off the walls. Capital Region Medical Center’s Dr. Chris Link says kids need at least 10 hours of sleep a night…',
  //   duration: '',
  //   station: 'KWOS',
  //   name: '2012_09_18',
  // },
  {
    date: 'November 20, 2012',
    title: 48,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2012_11_20',
  },
  {
    date: 'January 15, 2013',
    title: 49,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_01_15',
  },
  {
    date: 'February 19, 2013',
    title: 50,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_02_19',
  },
  {
    date: 'March 19, 2013',
    title: 51,
    description: 'Dr. Chris Link of Capital Region Medical Center’s Integrative Medicine Clinic talks about “food as medicine” in his latest visit to KWOS Open Air. This includes a healthy cup of coffee! Listen now:',
    duration: '16:59',
    station: 'KWOS',
    name: 'KWOS_2013_03_19',
  },
  {
    date: 'May 21, 2013',
    title: 52,
    description: 'Ticks, Travel, and Temper Tantrums',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_05_21',
  },
  {
    date: 'June 18, 2013',
    title: 53,
    description: 'Baseball, Hot Dogs, Apple Pie and…Kidney Stones?! Summertime can have some unpleasant side effects.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_06_18',
  },
  {
    date: 'July 16, 2013',
    title: 54,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_07_16',
  },
  {
    date: 'August 20, 2013',
    title: 55,
    description: 'Dr. Chris Link of Capital Region Medical Center’s Integrative Medicine Clinic has good advice for keeping your kids healthy as they go back to school. Listen now:',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_08_20',
  },
  {
    date: 'November 20, 2013',
    title: 56,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_11_20',
  },
  {
    date: 'December 17, 2013',
    title: 57,
    description: 'Dr. Chris Link of Capital Region Medical Center’s Integrative Medicine Clinic talks about the benefits of nuts, olive oil and more in his latest visit to KWOS Open Air:',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2013_12_17',
  },
  {
    date: 'January 21, 2014',
    title: 58,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_01_21',
  },
  {
    date: 'February 18, 2014',
    title: 59,
    description: 'Oiling Up The Ticker. With olive oil, that is. He has some heart healthy advice for February Heart Month:',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_02_18',
  },
  {
    date: 'March 18, 2014',
    title: 60,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_03_18',
  },
  {
    date: 'April 15, 2014',
    title: 61,
    description: 'Sardines & Coffee: Breakfast Of Champions. Well, maybe or maybe not, but we do talk about “food as medicine”',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_04_15',
  },
  {
    date: 'May 20, 2014',
    title: 62,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_05_20',
  },
  {
    date: 'June 17, 2014',
    title: 63,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_06_17',
  },
  {
    date: 'July 15, 2014',
    title: 64,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_07_15',
  },
  {
    date: 'August 19, 2014',
    title: 65,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_08_19',
  },
  {
    date: 'September 16, 2014',
    title: 66,
    description: 'Is Ebola really something you should worry about? It might be .. if you’re one of those several thousand military medical personnel who may be sent to West Africa. But Capital Region Medical Center’s Dr. Chris Link says be glad the disease isn’t as infectious as the flu …',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_09_16',
  },
  {
    date: 'October 23, 2014',
    title: 67,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_10_21',
  },
  {
    date: 'November 18, 2014',
    title: 68,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_11_18',
  },
  {
    date: 'December 16, 2014',
    title: 69,
    description: 'What are telomeres, and why should you care about yours?  We found out from Dr. Chris Link of Capital Region Medical Center’s Integrative Medicine Clinic.  Here’s his latest program on KWOS Open Air:',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2014_12_16',
  },
  {
    date: 'January 15, 2015',
    title: 70,
    description: 'Dr. Chris Link of Capital Region Medical Center’s Integrative Medicine Clinic has some healthy advice in his latest visit to KWOS Open Air:',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_01_15',
  },
  {
    date: 'February 17, 2015',
    title: 71,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_02_17',
  },
  {
    date: 'March 17, 2015',
    title: 72,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_03_17',
  },
  // {
  //   date: 'April 17, 2015',
  //   title: 73,
  //   description: '',
  //   duration: '',
  //   station: 'KWOS',
  //   name: '2015_04_17',
  // },
  {
    date: 'May 15, 2015',
    title: 74,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_05_15',
  },
  {
    date: 'June 16, 2015',
    title: 75,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_06_16',
  },
  {
    date: 'July 21, 2015',
    title: 76,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_07_21',
  },
  {
    date: 'November 17, 2015',
    title: 77,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2015_11_17',
  },
  {
    date: 'December 15, 2015',
    title: 78,
    description: '',
    duration: '16:04',
    station: 'KWOS',
    name: 'KWOS_2015_12_15',
  },
  {
    date: 'January 19, 2016',
    title: 79,
    description: 'Indigestion',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_01_19',
  },
  {
    date: 'February 16, 2016',
    title: 80,
    description: 'Indigestion',
    duration: '15:41',
    station: 'KWOS',
    name: 'KWOS_2016_02_16',
  },
  {
    date: 'March 16, 2016',
    title: 81,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_03_16',
  },
  {
    date: 'May 17, 2016',
    title: 82,
    description: 'Dr. Chris Link appeared for his regular interview on KWOS Open Air.  He talked about dangers associated with the”purple pill” and other antibiotics.  His interview is below.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_05_17',
  },
  {
    date: 'June 21, 2016',
    title: 83,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_06_21',
  },
  {
    date: 'July 19, 2016',
    title: 84,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_07_19',
  },
  {
    date: 'August 16, 2016',
    title: 85,
    description: 'In a figure that Doctor Chris Link has kept track of, he made his 85th appearance on KWOS Open Air.  We can only hope he makes it to 100 ',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_08_16',
  },
  {
    date: 'September 20, 2016',
    title: 86,
    description: 'Dr. Chris Link made his monthly appearance on KWOS Open Air to talk about your eye health and “tennis elbow.”  His interview is below.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_09_20',
  },
  {
    date: 'October 18, 2016',
    title: 87,
    description: 'Dr. Chris Link from Capital Region Medical Center appeared on KWOS’ Open Air for his monthly visit to discuss calcium supplements and the dangers involved.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_10_18',
  },
  {
    date: 'November 15, 2016',
    title: 88,
    description: 'Capital Region Dr. Chris Link appeared on KWOS Open Air for his monthly visit to discuss cancer prevention and UTI’s.  His interview is below.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_11_15',
  },
  {
    date: 'December 20, 2016',
    title: 89,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2016_12_20',
  },
  {
    date: 'January 17, 2017',
    title: 90,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2017_01_17',
  },
  {
    date: 'February 21, 2017',
    title: 91,
    description: 'Air to talk about several health related items, including new information on drinking coffee.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2017_02_21',
  },
  {
    date: 'April 18, 2017',
    title: 92,
    description: 'Dr. Chris Link appeared on KWOS Open Air with John Marsh and Kelley Ray to talk about this time of year and how to handle allergies.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2017_04_18',
  },
  {
    date: 'May 16, 2017',
    title: 93,
    description: 'Dr. Chris Link made his monthly visit to KWOS Open Air to talk about new finding involving sweeteners and dementia.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2017_05_16',
  },
  {
    date: 'June 20, 2017',
    title: 94,
    description: 'He talked about several new medical discoveries, one of which includes eating chocolate to reduce AFIB.  His interview is posted below.',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2017_06_20',
  },
  // {
  //   date: 'July 18, 2017',
  //   title: 95,
  //   description: '',
  //   duration: '',
  //   station: 'KWOS',
  //   name: 'KWOS_2017_07_18',
  // },
  {
    date: 'September 19, 2017',
    title: 96,
    description: '',
    duration: '',
    station: 'KWOS',
    name: 'KWOS_2017_09_19',
  },
  {
    date: 'October 18, 2017',
    title: 97,
    description: 'We talked about sugar and the links to cancer, healthy avocados, and other healthy eating do’s and don’ts. Here’s the interview:',
    duration: '14:04',
    station: 'KWOS',
    name: 'KWOS_2017_10_18',
  },
  {
    date: 'November 21, 2017',
    title: 98,
    description: 'Dr. Chris Link has some suggestions about eating well at Thanksgiving. He then discusses some important and eye-opening medical studies on Type II diabetes, heart stents, hormones and alzheimer’s disease in women and acid reducers and their link to gastric cancer. The interview is below:',
    duration: '15:48',
    station: 'KWOS',
    name: 'KWOS_2017_11_21',
  },
  {
    date: 'January 16, 2018',
    title: 99,
    description: 'How\'s the flu with you? He talked about influenza outbreaks current and passed. He also passed along his tips for a healthy new year. His interview is posted below:',
    duration: '15:17',
    station: 'KWOS',
    name: 'KWOS_2018_01_16',
  },
  {
    date: 'April 18, 2018',
    title: 100,
    description: 'He talked about allergy medicines and kids, too much sitting and its effects on the brain and more of the latest medical studies. His interview is posted below.',
    duration: '14:25',
    station: 'KWOS',
    name: 'KWOS_2018_04_17',
  },
  // {
  //   date: 'May 15, 2018',
  //   title: 101,
  //   description: '',
  //   duration: '15:41',
  //   station: 'KWOS',
  //   name: '2018_05_15',
  // },
  {
    date: 'June 25, 2018',
    title: 102,
    description: 'Dr. Link talks mosquitoes, common drugs – uncommon effects and Vitamin D',
    duration: '15:03',
    station: 'KWOS',
    name: 'KWOS_2018_06_25',
  },
];

export default radioEpisodes